(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const s of document.querySelectorAll('link[rel="modulepreload"]'))a(s);new MutationObserver(s=>{for(const o of s)if(o.type==="childList")for(const r of o.addedNodes)r.tagName==="LINK"&&r.rel==="modulepreload"&&a(r)}).observe(document,{childList:!0,subtree:!0});function n(s){const o={};return s.integrity&&(o.integrity=s.integrity),s.referrerPolicy&&(o.referrerPolicy=s.referrerPolicy),s.crossOrigin==="use-credentials"?o.credentials="include":s.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(s){if(s.ep)return;s.ep=!0;const o=n(s);fetch(s.href,o)}})();const l={ua:{whybul:"Чому Болгарія?",quest:"Питання",review:"Відгуки",company:"Grosters Громадянство ЄС",h1:"Від мрії до паспорта",heroText:"",plusHead:"Чому саме Болгарія?",plusKey:"Болгарія — ваш ключ до Європи",plusTextKey:`Болгарія — це не лише гарна природа й Чорне море. Це ще й країна,
                            що відкриває двері до Євросоюзу. Паспорт Болгарії = 169 країн без
                            віз. Можливість легально працювати, вести бізнес і жити в
                            будь-якій країні ЄС. Подвійне громадянство дозволене — ви не
                            втрачаєте своє. Це — розумна інвестиція у ваше майбутнє.`,plusWhy:"Чому Болгарія, а не інші країни ЄС?",plusTextWhy:`В Італії чи Іспанії треба жити 10+ років. У Німеччині — складні
                            іспити. А Болгарія — це швидко: до 12 місяців, без обов’язкового
                            проживання, без втрати громадянства, без мовних тестів. Ви
                            отримуєте паспорт ЄС, не змінюючи кардинально свій стиль життя.
                            Для багатьох наших клієнтів — це найкраща альтернатива міграції`,plusChild:"Що дає паспорт Болгарії вашим дітям?",plusTextChild:`Болгарія — це не лише гарна природа й Чорне море. Це ще й країна, що
          відкриває двері до Євросоюзу. Паспорт Болгарії = 169 країн без віз.
          Можливість легально працювати, вести бізнес і жити в будь-якій країні
          ЄС. Подвійне громадянство дозволене — ви не втрачаєте своє. Це —
          розумна інвестиція у ваше майбутнє.`,rootHead:"",rootHeadText1:"",rootItem1:"",rootItem2:"",rootItem3:"",rootItem4:"",rootHeadText2:"",questSecond:"",ansSecond:"",questThird:"",ansThird:"",questFourth:"",ansFourth:"",questFifth:"",ansFifth:"",questSixth:"",ansSixth:""},en:{whybul:"Why Bulgaria?",quest:"Questions",review:"Reviews",company:"Grosters EU citizenship",h1:"From dream to passport",heroText:"",plusHead:"Why Bulgaria?",plusKey:" Bulgaria - your key to Europe",plusTextKey:`Bulgaria is not just about beautiful nature and the Black Sea. It is also a country
 that opens the door to the European Union. Bulgarian passport = 169 countries without
 visas. The opportunity to legally work, do business and live in
 any EU country. Dual citizenship is allowed - you do not
 lose yours. It is a smart investment in your future.`,plusWhy:"Why Bulgaria and not other EU countries?",plusTextWhy:`You have to live in Italy or Spain for 10+ years. Germany has difficult
 exams. And Bulgaria is fast: up to 12 months, no mandatory
 residence, no loss of citizenship, no language tests. You
 get an EU passport without radically changing your lifestyle.
                            For many of our clients, this is the best alternative to migration`,plusChild:"What does a Bulgarian passport give your children?",plusTextChild:`The European passport is about opportunities for generations. Admission to
 EU universities without high quotas and restrictions. Access to medical
 services. Social guarantees, visa-free travel, children can have
 access to the same benefits as children in Germany or France. You
 are creating a future for your family - right now`,rootHead:"",rootHeadText1:"",rootItem1:"",rootItem2:"",rootItem3:"",rootItem4:"",rootHeadText2:"",questHead:"",questFirst:"",ansFirst:"",questSecond:"",ansSecond:"",questThird:"",ansThird:"",questFourth:"",ansFourth:"",questFifth:"",ansFifth:"",questSixth:"",ansSixth:""},bg:{whybul:"Защо България?",quest:"Въпрос",review:"Отзиви",company:"Гражданство на ЕС от Grosters",h1:"От мечта до паспорт",heroText:"",plusHead:"Защо България?",plusKey:"България - вашият ключ към Европа",plusTextKey:`България не е само красива природа и Черно море. Тя е и страна
, която отваря вратата към Европейския съюз. Български паспорт = 169 държави без визи
. Възможност за легална работа, бизнес и живот в
 всяка страна от ЕС. Двойното гражданство е разрешено - не
 губите своето. Това е разумна инвестиция във вашето бъдеще.`,plusWhy:"Защо България, а не други страни от ЕС?",plusTextWhy:`Трябва да сте живели в Италия или Испания над 10 години. В Германия има трудни изпити
. А в България е бързо: до 12 месеца, без задължително пребиваване
, без загуба на гражданство, без езикови тестове. Можете да
 получите паспорт на ЕС, без да променяте коренно начина си на живот.
                            За много от нашите клиенти това е най-добрата алтернатива на миграцията`,plusChild:"Какво дава българският паспорт на децата ви?",plusTextChild:`Европейският паспорт е свързан с възможностите за поколенията. Прием в
 университети в ЕС без високи квоти и ограничения. Достъп до медицински услуги
. Социални гаранции, безвизово пътуване, децата могат да имат
 достъп до същите придобивки като децата в Германия или Франция. Вие
 създавате бъдеще за семейството си - точно сега`,rootHead:"",rootHeadText1:"",rootItem1:"",rootItem2:"",rootItem3:"",rootItem4:"",rootHeadText2:"",questSecond:"",ansSecond:"",questThird:"",ansThird:"",questFourth:"",ansFourth:"",questFifth:"",ansFifth:"",questSixth:"",ansSixth:""}},c=document.querySelector(".burger-btn"),i=document.querySelector(".mobile-menu"),d=document.querySelector(".mobile-menu-icon-close"),h=document.querySelector(".mobile-menu-navigation-list");c.addEventListener("click",()=>{document.body.classList.add("no-scroll"),i.classList.add("is-open")});d.addEventListener("click",()=>{document.body.classList.remove("no-scroll"),i.classList.remove("is-open")});h.addEventListener("click",e=>{e.target.classList.contains("mobile-menu-navigation-list-link")&&(document.body.classList.remove("no-scroll"),i.classList.remove("is-open"),console.log(e.target)),console.log(e.target)});document.addEventListener("DOMContentLoaded",function(){new Splide("#bulgaria-slider",{type:"loop",autoplay:!0,interval:5e4,pauseOnHover:!0,pagination:!0,arrows:!0,speed:800}).mount()});const m=document.querySelectorAll(".accordion-button");m.forEach(e=>{e.addEventListener("click",()=>{const t=e.nextElementSibling;document.querySelectorAll(".accordion-content").forEach(n=>{n!==t&&(n.style.maxHeight=null)}),t.style.maxHeight=t.style.maxHeight?null:t.scrollHeight+"px"})});document.addEventListener("DOMContentLoaded",function(){const e=document.querySelectorAll(".advantages-item"),t=document.querySelector(".root-section");new IntersectionObserver(a=>{a.forEach(s=>{s.isIntersecting&&e.forEach((o,r)=>{o.style.opacity="0",o.style.transform="translateY(20px)",o.style.transition="none",setTimeout(()=>{o.style.transition="opacity 1s ease, transform 1s ease",o.style.opacity="1",o.style.transform="translateY(0)"},r*700)})})},{threshold:.3}).observe(t)});const y=new IntersectionObserver(e=>{e.forEach(t=>{t.isIntersecting&&t.target.classList.add("visible")})});document.querySelectorAll(".fade-in").forEach(e=>y.observe(e));let p=document.getElementById("myBtn");function f(){document.body.scrollTop=0,document.documentElement.scrollTop=0}p.addEventListener("click",f);function u(e){document.querySelectorAll("[data-i18n]").forEach(t=>{const n=t.getAttribute("data-i18n");l[e][n]&&(t.textContent=l[e][n])})}document.querySelectorAll(".lang-btn").forEach(e=>{e.addEventListener("click",()=>{const t=e.dataset.lang;u(t),localStorage.setItem("language",t)})});window.addEventListener("DOMContentLoaded",()=>{const e=localStorage.getItem("language")||"ua";u(e)});
//# sourceMappingURL=index.js.map
