const translations = {
  ua: {
    bulgaria: `Болгарія`,
    romania: `Румунія`,
    hungary:`Угорщина`,
    company: 'Grosters Громадянство ЄС',
    h1: 'Від мрії до паспорта',
    heroText: `Юридична компанія, яка допомагає легально отримати громадянство ЄС —
    від консультації до паспорта🛂 <br /><br />🔹 Працюємо офіційно <br />🔹
    Індивідуальний підхід <br />🔹 500+ клієнтів уже з паспортом<br /><br />
    Хочете жити в ЄС, подорожувати без віз, дати дітям освіту в Європі?
    Переходьте за посиланням або телефонуйте вже зараз📞`,
    rootHead: `Як отримати паспорт по корінню?`,
    rootHeadText1: `Це — не міф, а реальність! Ви можете стати громадянином ЄС усього за рік.
      Найшвидший і легальний шлях — походження (коріння):`,
    rootItem1: `Встановити родинний зв’язок`,
    rootItem2: `Знайти документи у архівах`,
    rootItem3: `Підготувати повний пакет документів`,
    rootItem4: `Перекласти, легалізувати, подати`,
    rootHeadText2: `Процес виглядає складно, але ми зробимо все за вас. Вам залишиться лише дочекатись позитивного рішення — і отримати паспорт. Напишіть нам - безкоштовна перевірка по корінню вже сьогодні!`,
    eduHead: `Освіта, досвід, експертність`,
    eduText: `Наша експертиза — ваша впевненість`,
    eduTextSecond: `Grosters — це не просто юридична компанія. <br /> Ми — команда з глибокими академічними знаннями та практичним досвідом:`,
    eduListFirst: `Консультанти — доктори юридичних наук, судді, адвокати, нотаріуси`,
    eduListSecond: `Співпрацюємо з провідними університетами України та ЄС`,
    eduListThird: `Публікації у міжнародних наукових журналах`,
    eduListFourth: `Підтримка освітніх та наукових програм за кордоном`,
    eduListFifth: `Допомагаємо зі стажуванням та навчанням у Європі`,
    eduLTextThird: `Ми не просто готуємо документи — ми розробляємо стратегії майбутнього для вас і вашої родини.`,
    eduLTextMore: `Більше про наші наукові та освітні напрямки:`,
    eduListSixth: `Співпрацюємо з провідними університетами України та ЄС`,
    reviewHead: `Відгуки наших клієнтів — найкраща рекомендація`,
    reviewstext: `Ми — юридична фірма, а не просто "фірма з оформлення". <br />
      📌 Наші юристи акредитовані <br />📌 Документи подаються офіційно, через
      державні установи <br />📌 Всі договори — юридично захищені <br />🛑 Ми не
      працюємо "по знайомству", не обіцяємо “в обхід закону” <br />💡 Наш
      головний інструмент — право і досвід, а не “зв’язки” Вибирай легальність =
      спокійне майбутнє`,
    reviewListHeadFirst: `Андрій С., Одеса`,
    reviewListTextFirst: `Працюють з повагою до клієнта. Допомогли не лише мені, а й моїм батькам.`,
    reviewListHeadSecond: `Олег В., Львів`,
    reviewListTextSecond: `Професійний підхід. Отримав не лише документи, а й повну консультацію`,
    reviewListHeadThird: `Всеволод М., Київ`,
    reviewListTextThird: `Дякую команді за повний супровід! Усе прозоро, швидко й офіційно.`,
    reviewListHeadFourth: `Марія Л., Харків`,
    reviewListTextFourth: `Отримала громадянство за 11 місяців. Усе чітко по етапах, як і обіцяли.`,
    diffHead: `Чим ми відрізняємося від інших компаній?`,
    diffSlogan: `Ми — юридична фірма, а не просто "фірма з оформлення" <span><i class="fa-solid fa-user-tie" style="color: #d4af37"></i></span>`,
    diffListHead: `Акредитовані юристи`,
    diffListTextFirst: `Наші юристи мають офіційну акредитацію та багаторічний досвід`,
    diffListHeadSecond: `Офіційне подання`,
    diffListTextSecond: `Документи подаються офіційно, через державні установи`,
    diffListHeadThird: `Юридичний захист`,
    diffListTextThird: `Всі договори юридично захищені, повна прозорість процесу`,
    diffStatus: `Поточний статус законопроєкту №11469 <span><i class="fa-solid fa-scale-balanced" style="color: #d4af37"></i></span>`,
    diffStatusText: `<span class="questions-span"><i class="fa-solid fa-check" style="color: #228b22"></i></span> Зареєстрований у <strong>Верховній Раді України</strong>`,
    diffStatusTextSecond: `<span class="questions-span"><i class="fa-solid fa-check" style="color: #228b22"></i></span> Пройшов <strong>перше читання </strong>`,
    diffStatusTextThird: `<span class="questions-span"><i class="fa-solid fa-check" style="color: #228b22"></i></span> Отримав <strong>позитивний висновок профільного комітету</strong>`,
    diffStatusTextFourth: `<span class="questions-span"><i class="fa-solid fa-check" style="color: #228b22"></i></span>  <strong>Схвалений у другому читанні</strong> Верховною Радою`,
    diffFake: `На жаль, ринок повний "сірих" пропозицій. Фейкові документи Прискорення “за гроші” Шахрайство. Ми ж працюємо винятково в правовому полі. Довіра починається з чесності. І ми цінуємо кожного, хто обирає її.`,
    todoHead: `Що робити вже сьогодні?`,
    mainPage: `Головна сторінка`,
    todoText: `Якщо ви дочитали досі — ви вже зробили перший крок! Що далі? Напишіть у Direct — ми перевіримо, чи підходить вам програма. Отримайте безкоштовну консультацію. Оберіть оптимальний шлях. Підпишіть договір — і ми беремо справу під свій контроль. Ваш паспорт = ваша свобода. Дійте сьогодні — не відкладайте на “потім” <span><i class="fa-solid fa-arrow-down" style="color: #d4af37"></i></span>`,
    footSlogan: `Хочеш паспорт ЄС без зайвих клопотів? Допомагаємо отримати громадянство Болгарії:<br /> Без переїзду<br />Без знання мови <br />Без стресу – усе під ключ!`,
    toTop: `Догори`,
  },
  en: {
    bulgaria: `Bulgaria`,
    romania: `Romania`,
    hungary:`Hungary`,
    company: 'Grosters EU citizenship',
    h1: 'From dream to passport',
    heroText: `A legal company that helps you obtain EU citizenship —
        from consultation to passport🛂 <br /><br />🔹 Official services <br />🔹
        Personalized approach <br />🔹 500+ clients already have passports<br /><br />
        Want to live in the EU, travel visa-free, and give your kids education in Europe?
        Follow the link or call us now📞`,
    rootHead: `How do I get a passport by root?`,
    rootHeadText1: `This is not a myth, but reality! You can become an EU citizen in just one year. The fastest and legal way is through origin (roots):`,
    rootItem1: `Establish a family connection`,
    rootItem2: `Find documents in archives`,
    rootItem3: `Prepare a full package of documents`,
    rootItem4: `Translate, legalise, submit`,
    rootHeadText2: `The process looks complicated, but we will do everything for you. All you have to do is wait for a positive decision and get your passport. Contact us for a free root check today!`,
    eduHead: `Education, experience, expertise`,
    eduText: `Our expertise - your confidence`,
    eduTextSecond: `Grosters is not just a law firm. <br/>We are a team with deep academic knowledge and practical experience:`,
    eduListFirst: `Consultants - doctors of law, judges, attorneys, notaries`,
    eduListSecond: `We cooperate with leading universities in Ukraine and the EU`,
    eduListThird: `Publications in international scientific journals`,
    eduListFourth: `Support for educational and research programmes abroad`,
    eduListFifth: `We help with internships and studies in Europe`,
    eduLTextThird: `We do not just prepare documents - we develop strategies for the future for you and your family.`,
    eduLTextMore: `Learn more about our research and education areas:`,
    eduListSixth: `We cooperate with leading universities in Ukraine and the EU`,
    reviewHead: `Our customers' reviews are the best recommendation`,
    reviewstext: `We are a law firm, not just a ‘registration company’.<br />
      📌 Our lawyers are accredited <br />📌 Documents are submitted officially through state institutions<br />📌  All contracts are legally protected<br />🛑  We do not work through connections, we do not promise to ‘circumvent the law’ <br />💡 Our main tools are the law and experience, not ‘connections’ Choose legality = a peaceful future`,
    reviewListHeadFirst: `Andriy S., Odessa`,
    reviewListTextFirst: `They work with respect for the customer. They helped not only me, but also my parents.`,
    reviewListHeadSecond: `Oleg V., Lviv`,
    reviewListTextSecond: `Professional approach. I received not only documents, but also comprehensive advice.`,
    reviewListHeadThird: `Vsevolod M., Kyiv`,
    reviewListTextThird: `Thank you to the team for their comprehensive support! Everything was transparent, fast and official.`,
    reviewListHeadFourth: `Maria L., Kharkiv`,
    reviewListTextFourth: `I obtained citizenship in 11 months. Everything went smoothly, step by step, just as promised.`,
    diffHead: `What makes us different from other companies?`,
    diffSlogan: `We are a law firm, not just a ‘registration firm’ <span><i class="fa-solid fa-user-tie" style="color: #d4af37"</i></span>`,
    diffListHead: `Accredited lawyers`,
    diffListTextFirst: `Our lawyers are officially accredited and have many years of experience`,
    diffListHeadSecond: `Legal application`,
    diffListTextSecond: `Documents are submitted officially, through government agencies`,
    diffListHeadThird: `Advocacy and legal protection`,
    diffListTextThird: `All contracts are legally protected, full transparency of the process`,
    diffStatus: `Current status of the draft law No. 11469 <span><i class="fa-solid fa-scale-balanced" style="color: #d4af37"></i></span>`,
    diffStatusText: `<span class="questions-span"><i class="fa-solid fa-check" style="color: #228b22"></i></span> Registered in the <strong> Verkhovna Rada of Ukraine</strong>`,
    diffStatusTextSecond: `<span class="questions-span"><i class="fa-solid fa-check" style="color: #228b22"></i></span> Passed the <strong>first reading</strong>`,
    diffStatusTextThird: `<span class="questions-span"><i class="fa-solid fa-check" style="color: #228b22"></i></span> Received a <strong>positive conclusion of the specialised committee</strong>`,
    diffStatusTextFourth: `<span class="questions-span"><i class="fa-solid fa-check" style="color: #228b22"></i></span>  <strong>Approved in the second reading by </strong> the Verkhovna Rada`,
    diffFake: `Unfortunately, the market is full of ‘grey’ offers. Fake documents Expediting for money Fraud. We work exclusively in the legal field. Trust begins with honesty. And we appreciate everyone who chooses it.`,
    todoHead: `What to do today?`,
    mainPage: `Main page`,
    todoText: `If you have read this far, you have already taken the first step! What's next? Write to Direct and we'll check if the programme is right for you. Get a free consultation. Choose the best way. Sign the agreement and we will take control of the case. Your passport = your freedom. Act today - don't put it off for later <span><i class="fa-solid fa-arrow-down" style="color: #d4af37"></i></span>`,
    footSlogan: `Do you want an EU passport without any hassle? We help you obtain Bulgarian citizenship: <br /> No relocation required <br /> No language skills <br /> No stress - everything is ready to go!`,
    toTop: `Top`,
  },
  ru: {
    bulgaria: `Болгария`,
    romania: `Румыния`,
    hungary:`Венгрия`,
    company: 'Grosters Гражданство ЕС',
    h1: 'От мечты к паспорту',
    heroText: `Юридическая компания, которая помогает легально получить гражданство ЕС — от консультации до паспорта 🛂 <br /><br />🔹 Работаем официально <br />🔹
        Индивидуальный подход <br />🔹500+ клиентов уже с паспортом<br /><br />
        Хотите жить в ЕС, путешествовать без виз, дать детям образование в Европе? Переходите по ссылке или звоните уже сейчас📞`,
    rootHead: `Как получить паспорт по корням?`,
    rootHeadText1: `Это — не миф, а реальность! Вы можете стать гражданином ЕС всего за год. Самый быстрый и легальный путь — происхождение (корни):`,
    rootItem1: `Установить родственную связь`,
    rootItem2: `Найти документы в архивах`,
    rootItem3: `Подготовить полный пакет документов`,
    rootItem4: `Перевести, легализовать, подать`,
    rootHeadText2: `Процесс выглядит сложным, но мы сделаем все за вас. Вам останется только дождаться положительного решения — и получить паспорт. Напишите нам — бесплатная проверка по корню уже сегодня!`,
    eduHead: `Образование, опыт, экспертность`,
    eduText: `Наша экспертиза — ваша уверенность`,
    eduTextSecond: `Grosters — это не просто юридическая компания. Мы — команда с глубокими академическими знаниями и практическим опытом:`,
    eduListFirst: `Консультанты — доктора юридических наук, судьи, адвокаты, нотариусы`,
    eduListSecond: `Сотрудничаем с ведущими университетами Украины и ЕС`,
    eduListThird: `Публикации в международных научных журналах`,
    eduListFourth: `Поддержка образовательных и научных программ за рубежом`,
    eduListFifth: `Помогаем со стажировкой и обучением в Европе`,
    eduLTextThird: `Мы не просто готовим документы — мы разрабатываем стратегии будущего для вас и вашей семьи.`,
    eduLTextMore: `Больше о наших научных и образовательных направлениях:`,
    eduListSixth: `Сотрудничаем с ведущими университетами Украины и ЕС`,
    reviewHead: `Отзывы наших клиентов — лучшая рекомендация`,
    reviewstext: `Мы — юридическая фирма, а не просто «фирма по оформлению».<br />
      📌 Наши юристы аккредитованы<br />📌 Документы подаются официально, через государственные учреждения<br />📌   Все договоры — юридически защищены<br />🛑  Мы не работаем «по знакомству», не обещаем «в обход закона»<br />💡Наш главный инструмент — право и опыт, а не «связи» Выбирай легальность = спокойное будущее`,
    reviewListHeadFirst: `Андрей С., Одесса`,
    reviewListTextFirst: `Работают с уважением к клиенту. Помогли не только мне, но и моим родителям.`,
    reviewListHeadSecond: `Олег В., Львов`,
    reviewListTextSecond: `Профессиональный подход. Получил не только документы, но и полную консультацию`,
    reviewListHeadThird: `Всеволод М., Киев`,
    reviewListTextThird: `Спасибо команде за полное сопровождение! Все прозрачно, быстро и официально.`,
    reviewListHeadFourth: `Мария Л., Харьков`,
    reviewListTextFourth: `Получила гражданство за 11 месяцев. Все четко по этапам, как и обещали.`,
    diffHead: `Чем мы отличаемся от других компаний?`,
    diffSlogan: `Мы — юридическая фирма, а не просто «фирма по оформлению»<span><i class="fa-solid fa-user-tie" style="color: #d4af37"</i></span>`,
    diffListHead: `Аккредитованные юристы`,
    diffListTextFirst: `Наши юристы имеют официальную аккредитацию и многолетний опыт`,
    diffListHeadSecond: `Официальное представление`,
    diffListTextSecond: `Документы подаются официально, через государственные учреждения`,
    diffListHeadThird: `Юридическая защита`,
    diffListTextThird: `Все договоры юридически защищены, полная прозрачность процесса`,
    diffStatus: `Текущий статус законопроекта №11469<span><i class="fa-solid fa-scale-balanced" style="color: #d4af37"></i></span>`,
    diffStatusText: `<span class="questions-span"><i class="fa-solid fa-check" style="color: #228b22"></i></span> Зарегистрирован в <strong> Верховной Раде Украины</strong>`,
    diffStatusTextSecond: `<span class="questions-span"><i class="fa-solid fa-check" style="color: #228b22"></i></span> Прошел <strong>первое чтение</strong>`,
    diffStatusTextThird: `<span class="questions-span"><i class="fa-solid fa-check" style="color: #228b22"></i></span> Получил <strong>положительное заключение профильного комитета</strong>`,
    diffStatusTextFourth: `<span class="questions-span"><i class="fa-solid fa-check" style="color: #228b22"></i></span> <strong>Одобрен во втором чтении</strong> Верховной Радой`,
    diffFake: `К сожалению, рынок полон «серых» предложений. Фейковые документы. Ускорение «за деньги». Мошенничество. Мы же работаем исключительно в правовом поле. Доверие начинается с честности. И мы ценим каждого, кто выбирает ее.`,
    todoHead: `Что делать уже сегодня?`,
    mainPage: `Главная страница`,
    todoText: `Если вы дочитали до этого места — вы уже сделали первый шаг! Что дальше? Напишите в Direct — мы проверим, подходит ли вам программа. Получите бесплатную консультацию. Выберите оптимальный путь. Подпишите договор — и мы берем дело под свой контроль. Ваш паспорт = ваша свобода. Действуйте сегодня — не откладывайте на «потом».<span><i class="fa-solid fa-arrow-down" style="color: #d4af37"></i></span>`,
    footSlogan: `Хочешь паспорт ЕС без лишних хлопот? Помогаем получить гражданство Болгарии:<br /> Без переезда <br /> Без знания языка<br /> Без стресса – все под ключ!`,
    toTop: `Вверх`,
  },
};
export default translations;
